server:
  port: 8081
spring:
  application:
    name: item-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/heima?useUnicode=true&characterEncoding=utf8&useSSL=true
    username: root
    password: 123456
    hikari:
      maximum-pool-size: 30
      minimum-idle: 10
  rabbitmq:
    host: 182.254.227.85
    username: leyou
    password: 123
    virtual-host: /
    template:
      retry:
        enabled: true
        initial-interval: 10000ms
        max-interval: 300000ms
        multiplier: 2
      exchange: ly.item.exchange
    publisher-confirms: true
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5 # 每隔5秒发送一次心跳
    lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl